<% repo_root = File.expand_path("../..", __dir__) %>

service: polaris_form_builder-playground
image: lexcao/polaris_form_builder-playground

servers:
  web:
    - <%= ENV.fetch("SERVER_IP") %>

proxy:
  ssl: true
  host: polaris-form-builder.lexcao.io

registry:
  server: localhost:5555

builder:
  arch: amd64
  context: <%= repo_root %>
  dockerfile: <%= File.join(repo_root, "app/playground/Dockerfile") %>

env:
  secret:
    - RAILS_MASTER_KEY
