name: CI

on:
  pull_request:
    types: [ opened, synchronize ]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Install system packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y libsqlite3-0 libvips curl ffmpeg

      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version

      - name: Run CI
        run: bin/ci
